
name: Build and push Fibonacci Docker image

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags:
      - "ver*.*.*"

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          # ${{ secrets.DOCKER_HUB_USERNAME }}/simple_fibonacci
          ghcr.io/${{ github.repository_owner }}/simple_fibonacci
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_ACCESS_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: |
          type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/simple_fibonacci:cache
        cache-to: |
          type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/simple_fibonacci:cache