name: Build and push Docker image

on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_ACESS_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            app=fibonacci
            author=${AUTHOR_NAME}
            group=${GROUP_NUMBER}
          cache-from: |
            type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/python-fibonacci:cache
          cache-to: |
            type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/python-fibonacci:cache
